# Generated by Django 5.2 on 2025-04-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactus",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
            },
        ),
        migrations.AddField(
            model_name="contactus",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="subject",
            field=models.CharField(max_length=200),
        ),
    ]
