# Generated by Django 5.2 on 2025-04-21 16:30

import django.db.models.deletion
import utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurePaymentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_holder_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_four_digits",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("encrypted_data_cc_number", models.TextField(blank=True, null=True)),
                ("encryption_salt_cc_number", models.TextField(blank=True, null=True)),
                ("encrypted_data_cc_expiry", models.TextField(blank=True, null=True)),
                ("encryption_salt_cc_expiry", models.TextField(blank=True, null=True)),
                ("encrypted_data_cc_cvv", models.TextField(blank=True, null=True)),
                ("encryption_salt_cc_cvv", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secure_payment",
                        to="cart.transaction",
                    ),
                ),
            ],
            bases=(models.Model, utils.models.EncryptedTextFieldMixin),
        ),
    ]
